# Generated by Django 5.2.6 on 2025-09-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_support', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportrequest',
            old_name='subject',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='supportrequest',
            old_name='message',
            new_name='description',
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='category',
            field=models.CharField(choices=[('DEPED ACCOUNTS - CREATE', 'DEPED ACCOUNTS - CREATE'), ('DEPED ACCOUNTS - RESET', 'DEPED ACCOUNTS - RESET'), ('DEPED ACCOUNTS - EXPIRED', 'DEPED ACCOUNTS - EXPIRED'), ('HARDWARE', 'HARDWARE'), ('SOFTWARE', 'SOFTWARE'), ('INTERNET', 'INTERNET'), ('OTHERS', 'OTHERS')], default='HARDWARE', max_length=50),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='priority',
            field=models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], default='LOW', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=10),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='ticket_number',
            field=models.CharField(default=0, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
