# Generated by Django 5.2.6 on 2025-09-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_support', '0002_rename_subject_supportrequest_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='process',
            field=models.CharField(blank=True, choices=[('RAFAEL AMORANTO', 'RAFAEL AMORANTO'), ('JACOB BENAVIDIES', 'JACOB BENAVIDIES'), ('LESTER RAMOS', 'LESTER RAMOS'), ('SELWYN RANER', 'SELWYN RANER')], max_length=50, null=True),
        ),
    ]
