# Generated by Django 5.2.6 on 2025-09-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_support', '0004_alter_supportrequest_process_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportrequest',
            name='id',
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='ticket_number',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
