# Generated by Django 5.2.6 on 2025-09-25 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_support', '0004_alter_supportrequest_process_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_number', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=100)),
                ('support_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_app', to='user_support.supportrequest')),
            ],
        ),
    ]
