# Generated by Django 5.2.6 on 2025-09-25 07:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='rm_number',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='support_request',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='equipment',
            field=models.CharField(blank=True, choices=[('Desktop', 'Desktop'), ('Laptop', 'Laptop')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='maintenance_type',
            field=models.CharField(blank=True, choices=[('REPAIR', 'REPAIR'), ('NON REPAIR', 'NON REPAIR')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='office',
            field=models.CharField(blank=True, choices=[('OSDS', 'OSDS'), ('CID', 'CID'), ('SGOD', 'SGOD')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='priority',
            field=models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], default='LOW', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='rm_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='RM No.'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='schedule_category',
            field=models.CharField(choices=[('SCHEDULED', 'SCHEDULED'), ('UNSCHEDULED', 'UNSCHEDULED')], default='UNSCHEDULED', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='ticket',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='ticket_status',
            field=models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial Number'),
        ),
    ]
