# Generated by Django 5.2.6 on 2025-09-25 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_app', '0002_remove_maintenance_rm_number_and_more'),
        ('user_support', '0005_remove_supportrequest_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_support.supportrequest'),
        ),
    ]
